version: "3.3"

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5555:5432"

  web:
    build:
      dockerfile: ./src/django_project/Dockerfile
    container_name: loans
    hostname: loans
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres_data:
